//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtosalonEntities13 : DbContext
    {
        public AvtosalonEntities13()
            : base("name=AvtosalonEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<Договор> Договор { get; set; }
        public virtual DbSet<Доп_услуги> Доп_услуги { get; set; }
        public virtual DbSet<Доп_услуги_авто> Доп_услуги_авто { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Коробка_передач> Коробка_передач { get; set; }
        public virtual DbSet<Кузов> Кузов { get; set; }
        public virtual DbSet<Паспорт> Паспорт { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Список_моделей> Список_моделей { get; set; }
        public virtual DbSet<Тип_пользователя> Тип_пользователя { get; set; }
        public virtual DbSet<ТО> ТО { get; set; }
        public virtual DbSet<Характеристики> Характеристики { get; set; }
    }
}
