//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.Доп_услуги_авто = new HashSet<Доп_услуги_авто>();
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код_авто { get; set; }
        public Nullable<int> Код_модели { get; set; }
        public Nullable<int> Код_ТО { get; set; }
        public string Описание { get; set; }
        public string Цена { get; set; }
        public Nullable<int> Код_доп_услуг { get; set; }
        public Nullable<int> Код_характеристик { get; set; }
        public string Фото { get; set; }
    
        public virtual Доп_услуги Доп_услуги { get; set; }
        public virtual Список_моделей Список_моделей { get; set; }
        public virtual ТО ТО { get; set; }
        public virtual Характеристики Характеристики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Доп_услуги_авто> Доп_услуги_авто { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
    }
}
