//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договор
    {
        public int Код_договора { get; set; }
        public Nullable<int> Код_заявки { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Заявка Заявка { get; set; }
    }
}
