//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Доп_услуги_авто
    {
        public int Код_доп_услуг_авто { get; set; }
        public string Количество { get; set; }
        public Nullable<int> Код_доп_услуг { get; set; }
        public Nullable<int> Код_авто { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Доп_услуги Доп_услуги { get; set; }
    }
}
