//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.Договор = new HashSet<Договор>();
        }
    
        public int Код_заявки { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public Nullable<int> Код_авто { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public string Итоговая_цена { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Договор> Договор { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
