//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код_сотрудника { get; set; }
        public string ФИО { get; set; }
        public string email { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<int> Код_типа_пользователя { get; set; }
        public string Фото { get; set; }
        public Nullable<bool> Статус { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        public virtual Тип_пользователя Тип_пользователя { get; set; }
    }
}
