//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Характеристики
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Характеристики()
        {
            this.Автомобили = new HashSet<Автомобили>();
        }
    
        public int Код_характеристик { get; set; }
        public string Скорость { get; set; }
        public string Масса { get; set; }
        public Nullable<int> Код_типа_коробки_передач { get; set; }
        public Nullable<int> Код_типа_кузова { get; set; }
        public string Номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Автомобили> Автомобили { get; set; }
        public virtual Коробка_передач Коробка_передач { get; set; }
        public virtual Кузов Кузов { get; set; }
    }
}
